/*
 * Generated by gdbus-codegen 2.48.2. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "dbus_wpas.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface fi.w1.wpa_supplicant1
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:FiW1Wpa_supplicant1
 * @title: FiW1Wpa_supplicant1
 * @short_description: Generated C code for the fi.w1.wpa_supplicant1 D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-fi-w1-wpa_supplicant1.top_of_page">fi.w1.wpa_supplicant1</link> D-Bus interface in C.
 */

/* ---- Introspection data for fi.w1.wpa_supplicant1 ---- */

static const _ExtendedGDBusArgInfo _fi_w1_wpa_supplicant1_method_info_get_interface_IN_ARG_interface =
{
  {
    -1,
    (gchar *) "interface",
    (gchar *) "s",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _fi_w1_wpa_supplicant1_method_info_get_interface_IN_ARG_pointers[] =
{
  &_fi_w1_wpa_supplicant1_method_info_get_interface_IN_ARG_interface,
  NULL
};

static const _ExtendedGDBusArgInfo _fi_w1_wpa_supplicant1_method_info_get_interface_OUT_ARG_path =
{
  {
    -1,
    (gchar *) "path",
    (gchar *) "o",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _fi_w1_wpa_supplicant1_method_info_get_interface_OUT_ARG_pointers[] =
{
  &_fi_w1_wpa_supplicant1_method_info_get_interface_OUT_ARG_path,
  NULL
};

static const _ExtendedGDBusMethodInfo _fi_w1_wpa_supplicant1_method_info_get_interface =
{
  {
    -1,
    (gchar *) "GetInterface",
    (GDBusArgInfo **) &_fi_w1_wpa_supplicant1_method_info_get_interface_IN_ARG_pointers,
    (GDBusArgInfo **) &_fi_w1_wpa_supplicant1_method_info_get_interface_OUT_ARG_pointers,
    NULL
  },
  "handle-get-interface",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _fi_w1_wpa_supplicant1_method_info_pointers[] =
{
  &_fi_w1_wpa_supplicant1_method_info_get_interface,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _fi_w1_wpa_supplicant1_interface_info =
{
  {
    -1,
    (gchar *) "fi.w1.wpa_supplicant1",
    (GDBusMethodInfo **) &_fi_w1_wpa_supplicant1_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "fi-w1-wpa-supplicant1",
};


/**
 * fi_w1_wpa_supplicant1_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-fi-w1-wpa_supplicant1.top_of_page">fi.w1.wpa_supplicant1</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
fi_w1_wpa_supplicant1_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_fi_w1_wpa_supplicant1_interface_info.parent_struct;
}

/**
 * fi_w1_wpa_supplicant1_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #FiW1Wpa_supplicant1 interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
fi_w1_wpa_supplicant1_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * FiW1Wpa_supplicant1:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-fi-w1-wpa_supplicant1.top_of_page">fi.w1.wpa_supplicant1</link>.
 */

/**
 * FiW1Wpa_supplicant1Iface:
 * @parent_iface: The parent interface.
 * @handle_get_interface: Handler for the #FiW1Wpa_supplicant1::handle-get-interface signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-fi-w1-wpa_supplicant1.top_of_page">fi.w1.wpa_supplicant1</link>.
 */

typedef FiW1Wpa_supplicant1Iface FiW1Wpa_supplicant1Interface;
G_DEFINE_INTERFACE (FiW1Wpa_supplicant1, fi_w1_wpa_supplicant1, G_TYPE_OBJECT);

static void
fi_w1_wpa_supplicant1_default_init (FiW1Wpa_supplicant1Iface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * FiW1Wpa_supplicant1::handle-get-interface:
   * @object: A #FiW1Wpa_supplicant1.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_interface: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-fi-w1-wpa_supplicant1.GetInterface">GetInterface()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call fi_w1_wpa_supplicant1_complete_get_interface() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-get-interface",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (FiW1Wpa_supplicant1Iface, handle_get_interface),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_STRING);

}

/**
 * fi_w1_wpa_supplicant1_call_get_interface:
 * @proxy: A #FiW1Wpa_supplicant1Proxy.
 * @arg_interface: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-fi-w1-wpa_supplicant1.GetInterface">GetInterface()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call fi_w1_wpa_supplicant1_call_get_interface_finish() to get the result of the operation.
 *
 * See fi_w1_wpa_supplicant1_call_get_interface_sync() for the synchronous, blocking version of this method.
 */
void
fi_w1_wpa_supplicant1_call_get_interface (
    FiW1Wpa_supplicant1 *proxy,
    const gchar *arg_interface,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "GetInterface",
    g_variant_new ("(s)",
                   arg_interface),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * fi_w1_wpa_supplicant1_call_get_interface_finish:
 * @proxy: A #FiW1Wpa_supplicant1Proxy.
 * @out_path: (out): Return location for return parameter or %NULL to ignore.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to fi_w1_wpa_supplicant1_call_get_interface().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with fi_w1_wpa_supplicant1_call_get_interface().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
fi_w1_wpa_supplicant1_call_get_interface_finish (
    FiW1Wpa_supplicant1 *proxy,
    gchar **out_path,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_path);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * fi_w1_wpa_supplicant1_call_get_interface_sync:
 * @proxy: A #FiW1Wpa_supplicant1Proxy.
 * @arg_interface: Argument to pass with the method invocation.
 * @out_path: (out): Return location for return parameter or %NULL to ignore.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-fi-w1-wpa_supplicant1.GetInterface">GetInterface()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See fi_w1_wpa_supplicant1_call_get_interface() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
fi_w1_wpa_supplicant1_call_get_interface_sync (
    FiW1Wpa_supplicant1 *proxy,
    const gchar *arg_interface,
    gchar **out_path,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "GetInterface",
    g_variant_new ("(s)",
                   arg_interface),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "(o)",
                 out_path);
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * fi_w1_wpa_supplicant1_complete_get_interface:
 * @object: A #FiW1Wpa_supplicant1.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 * @path: Parameter to return.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-fi-w1-wpa_supplicant1.GetInterface">GetInterface()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
fi_w1_wpa_supplicant1_complete_get_interface (
    FiW1Wpa_supplicant1 *object,
    GDBusMethodInvocation *invocation,
    const gchar *path)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("(o)",
                   path));
}

/* ------------------------------------------------------------------------ */

/**
 * FiW1Wpa_supplicant1Proxy:
 *
 * The #FiW1Wpa_supplicant1Proxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * FiW1Wpa_supplicant1ProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #FiW1Wpa_supplicant1Proxy.
 */

struct _FiW1Wpa_supplicant1ProxyPrivate
{
  GData *qdata;
};

static void fi_w1_wpa_supplicant1_proxy_iface_init (FiW1Wpa_supplicant1Iface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (FiW1Wpa_supplicant1Proxy, fi_w1_wpa_supplicant1_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (FiW1Wpa_supplicant1Proxy)
                         G_IMPLEMENT_INTERFACE (TYPE_FI_W1_WPA_SUPPLICANT1, fi_w1_wpa_supplicant1_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (FiW1Wpa_supplicant1Proxy, fi_w1_wpa_supplicant1_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_FI_W1_WPA_SUPPLICANT1, fi_w1_wpa_supplicant1_proxy_iface_init));

#endif
static void
fi_w1_wpa_supplicant1_proxy_finalize (GObject *object)
{
  FiW1Wpa_supplicant1Proxy *proxy = FI_W1_WPA_SUPPLICANT1_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (fi_w1_wpa_supplicant1_proxy_parent_class)->finalize (object);
}

static void
fi_w1_wpa_supplicant1_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
fi_w1_wpa_supplicant1_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
fi_w1_wpa_supplicant1_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_fi_w1_wpa_supplicant1_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_FI_W1_WPA_SUPPLICANT1);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_FI_W1_WPA_SUPPLICANT1);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
fi_w1_wpa_supplicant1_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  FiW1Wpa_supplicant1Proxy *proxy = FI_W1_WPA_SUPPLICANT1_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_fi_w1_wpa_supplicant1_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_fi_w1_wpa_supplicant1_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
fi_w1_wpa_supplicant1_proxy_init (FiW1Wpa_supplicant1Proxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = fi_w1_wpa_supplicant1_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_FI_W1_WPA_SUPPLICANT1_PROXY, FiW1Wpa_supplicant1ProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), fi_w1_wpa_supplicant1_interface_info ());
}

static void
fi_w1_wpa_supplicant1_proxy_class_init (FiW1Wpa_supplicant1ProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = fi_w1_wpa_supplicant1_proxy_finalize;
  gobject_class->get_property = fi_w1_wpa_supplicant1_proxy_get_property;
  gobject_class->set_property = fi_w1_wpa_supplicant1_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = fi_w1_wpa_supplicant1_proxy_g_signal;
  proxy_class->g_properties_changed = fi_w1_wpa_supplicant1_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (FiW1Wpa_supplicant1ProxyPrivate));
#endif
}

static void
fi_w1_wpa_supplicant1_proxy_iface_init (FiW1Wpa_supplicant1Iface *iface)
{
}

/**
 * fi_w1_wpa_supplicant1_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-fi-w1-wpa_supplicant1.top_of_page">fi.w1.wpa_supplicant1</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call fi_w1_wpa_supplicant1_proxy_new_finish() to get the result of the operation.
 *
 * See fi_w1_wpa_supplicant1_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
fi_w1_wpa_supplicant1_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_FI_W1_WPA_SUPPLICANT1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "fi.w1.wpa_supplicant1", NULL);
}

/**
 * fi_w1_wpa_supplicant1_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to fi_w1_wpa_supplicant1_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with fi_w1_wpa_supplicant1_proxy_new().
 *
 * Returns: (transfer full) (type FiW1Wpa_supplicant1Proxy): The constructed proxy object or %NULL if @error is set.
 */
FiW1Wpa_supplicant1 *
fi_w1_wpa_supplicant1_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return FI_W1_WPA_SUPPLICANT1 (ret);
  else
    return NULL;
}

/**
 * fi_w1_wpa_supplicant1_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-fi-w1-wpa_supplicant1.top_of_page">fi.w1.wpa_supplicant1</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See fi_w1_wpa_supplicant1_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type FiW1Wpa_supplicant1Proxy): The constructed proxy object or %NULL if @error is set.
 */
FiW1Wpa_supplicant1 *
fi_w1_wpa_supplicant1_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_FI_W1_WPA_SUPPLICANT1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "fi.w1.wpa_supplicant1", NULL);
  if (ret != NULL)
    return FI_W1_WPA_SUPPLICANT1 (ret);
  else
    return NULL;
}


/**
 * fi_w1_wpa_supplicant1_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like fi_w1_wpa_supplicant1_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call fi_w1_wpa_supplicant1_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See fi_w1_wpa_supplicant1_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
fi_w1_wpa_supplicant1_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_FI_W1_WPA_SUPPLICANT1_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "fi.w1.wpa_supplicant1", NULL);
}

/**
 * fi_w1_wpa_supplicant1_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to fi_w1_wpa_supplicant1_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with fi_w1_wpa_supplicant1_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type FiW1Wpa_supplicant1Proxy): The constructed proxy object or %NULL if @error is set.
 */
FiW1Wpa_supplicant1 *
fi_w1_wpa_supplicant1_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return FI_W1_WPA_SUPPLICANT1 (ret);
  else
    return NULL;
}

/**
 * fi_w1_wpa_supplicant1_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like fi_w1_wpa_supplicant1_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See fi_w1_wpa_supplicant1_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type FiW1Wpa_supplicant1Proxy): The constructed proxy object or %NULL if @error is set.
 */
FiW1Wpa_supplicant1 *
fi_w1_wpa_supplicant1_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_FI_W1_WPA_SUPPLICANT1_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "fi.w1.wpa_supplicant1", NULL);
  if (ret != NULL)
    return FI_W1_WPA_SUPPLICANT1 (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * FiW1Wpa_supplicant1Skeleton:
 *
 * The #FiW1Wpa_supplicant1Skeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * FiW1Wpa_supplicant1SkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #FiW1Wpa_supplicant1Skeleton.
 */

struct _FiW1Wpa_supplicant1SkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_fi_w1_wpa_supplicant1_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  FiW1Wpa_supplicant1Skeleton *skeleton = FI_W1_WPA_SUPPLICANT1_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_FI_W1_WPA_SUPPLICANT1);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_FI_W1_WPA_SUPPLICANT1);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_fi_w1_wpa_supplicant1_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  FiW1Wpa_supplicant1Skeleton *skeleton = FI_W1_WPA_SUPPLICANT1_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_fi_w1_wpa_supplicant1_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_fi_w1_wpa_supplicant1_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  FiW1Wpa_supplicant1Skeleton *skeleton = FI_W1_WPA_SUPPLICANT1_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_fi_w1_wpa_supplicant1_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _fi_w1_wpa_supplicant1_skeleton_vtable =
{
  _fi_w1_wpa_supplicant1_skeleton_handle_method_call,
  _fi_w1_wpa_supplicant1_skeleton_handle_get_property,
  _fi_w1_wpa_supplicant1_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
fi_w1_wpa_supplicant1_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return fi_w1_wpa_supplicant1_interface_info ();
}

static GDBusInterfaceVTable *
fi_w1_wpa_supplicant1_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_fi_w1_wpa_supplicant1_skeleton_vtable;
}

static GVariant *
fi_w1_wpa_supplicant1_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  FiW1Wpa_supplicant1Skeleton *skeleton = FI_W1_WPA_SUPPLICANT1_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_fi_w1_wpa_supplicant1_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _fi_w1_wpa_supplicant1_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _fi_w1_wpa_supplicant1_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _fi_w1_wpa_supplicant1_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "fi.w1.wpa_supplicant1", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
fi_w1_wpa_supplicant1_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void fi_w1_wpa_supplicant1_skeleton_iface_init (FiW1Wpa_supplicant1Iface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (FiW1Wpa_supplicant1Skeleton, fi_w1_wpa_supplicant1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (FiW1Wpa_supplicant1Skeleton)
                         G_IMPLEMENT_INTERFACE (TYPE_FI_W1_WPA_SUPPLICANT1, fi_w1_wpa_supplicant1_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (FiW1Wpa_supplicant1Skeleton, fi_w1_wpa_supplicant1_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_FI_W1_WPA_SUPPLICANT1, fi_w1_wpa_supplicant1_skeleton_iface_init));

#endif
static void
fi_w1_wpa_supplicant1_skeleton_finalize (GObject *object)
{
  FiW1Wpa_supplicant1Skeleton *skeleton = FI_W1_WPA_SUPPLICANT1_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (fi_w1_wpa_supplicant1_skeleton_parent_class)->finalize (object);
}

static void
fi_w1_wpa_supplicant1_skeleton_init (FiW1Wpa_supplicant1Skeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = fi_w1_wpa_supplicant1_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_FI_W1_WPA_SUPPLICANT1_SKELETON, FiW1Wpa_supplicant1SkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
fi_w1_wpa_supplicant1_skeleton_class_init (FiW1Wpa_supplicant1SkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = fi_w1_wpa_supplicant1_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = fi_w1_wpa_supplicant1_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = fi_w1_wpa_supplicant1_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = fi_w1_wpa_supplicant1_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = fi_w1_wpa_supplicant1_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (FiW1Wpa_supplicant1SkeletonPrivate));
#endif
}

static void
fi_w1_wpa_supplicant1_skeleton_iface_init (FiW1Wpa_supplicant1Iface *iface)
{
}

/**
 * fi_w1_wpa_supplicant1_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-fi-w1-wpa_supplicant1.top_of_page">fi.w1.wpa_supplicant1</link>.
 *
 * Returns: (transfer full) (type FiW1Wpa_supplicant1Skeleton): The skeleton object.
 */
FiW1Wpa_supplicant1 *
fi_w1_wpa_supplicant1_skeleton_new (void)
{
  return FI_W1_WPA_SUPPLICANT1 (g_object_new (TYPE_FI_W1_WPA_SUPPLICANT1_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for interface fi.w1.wpa_supplicant1.Outerface
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:FiW1Wpa_supplicant1Outerface
 * @title: FiW1Wpa_supplicant1Outerface
 * @short_description: Generated C code for the fi.w1.wpa_supplicant1.Outerface D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-fi-w1-wpa_supplicant1-Outerface.top_of_page">fi.w1.wpa_supplicant1.Outerface</link> D-Bus interface in C.
 */

/* ---- Introspection data for fi.w1.wpa_supplicant1.Outerface ---- */

static const _ExtendedGDBusArgInfo _fi_w1_wpa_supplicant1_outerface_method_info_scan_IN_ARG_args =
{
  {
    -1,
    (gchar *) "args",
    (gchar *) "a{sv}",
    NULL
  },
  FALSE
};

static const _ExtendedGDBusArgInfo * const _fi_w1_wpa_supplicant1_outerface_method_info_scan_IN_ARG_pointers[] =
{
  &_fi_w1_wpa_supplicant1_outerface_method_info_scan_IN_ARG_args,
  NULL
};

static const _ExtendedGDBusMethodInfo _fi_w1_wpa_supplicant1_outerface_method_info_scan =
{
  {
    -1,
    (gchar *) "Scan",
    (GDBusArgInfo **) &_fi_w1_wpa_supplicant1_outerface_method_info_scan_IN_ARG_pointers,
    NULL,
    NULL
  },
  "handle-scan",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _fi_w1_wpa_supplicant1_outerface_method_info_pointers[] =
{
  &_fi_w1_wpa_supplicant1_outerface_method_info_scan,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _fi_w1_wpa_supplicant1_outerface_interface_info =
{
  {
    -1,
    (gchar *) "fi.w1.wpa_supplicant1.Interface",
    (GDBusMethodInfo **) &_fi_w1_wpa_supplicant1_outerface_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "fi-w1-wpa-supplicant1-interface",
};


/**
 * fi_w1_wpa_supplicant1_outerface_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-fi-w1-wpa_supplicant1-Outerface.top_of_page">fi.w1.wpa_supplicant1.Outerface</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
fi_w1_wpa_supplicant1_outerface_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_fi_w1_wpa_supplicant1_outerface_interface_info.parent_struct;
}

/**
 * fi_w1_wpa_supplicant1_outerface_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #FiW1Wpa_supplicant1Outerface interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
fi_w1_wpa_supplicant1_outerface_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * FiW1Wpa_supplicant1Outerface:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-fi-w1-wpa_supplicant1-Outerface.top_of_page">fi.w1.wpa_supplicant1.Outerface</link>.
 */

/**
 * FiW1Wpa_supplicant1OuterfaceIface:
 * @parent_iface: The parent interface.
 * @handle_scan: Handler for the #FiW1Wpa_supplicant1Outerface::handle-scan signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-fi-w1-wpa_supplicant1-Outerface.top_of_page">fi.w1.wpa_supplicant1.Outerface</link>.
 */

typedef FiW1Wpa_supplicant1OuterfaceIface FiW1Wpa_supplicant1OuterfaceInterface;
G_DEFINE_INTERFACE (FiW1Wpa_supplicant1Outerface, fi_w1_wpa_supplicant1_outerface, G_TYPE_OBJECT);

static void
fi_w1_wpa_supplicant1_outerface_default_init (FiW1Wpa_supplicant1OuterfaceIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * FiW1Wpa_supplicant1Outerface::handle-scan:
   * @object: A #FiW1Wpa_supplicant1Outerface.
   * @invocation: A #GDBusMethodInvocation.
   * @arg_args: Argument passed by remote caller.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-fi-w1-wpa_supplicant1-Outerface.Scan">Scan()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call fi_w1_wpa_supplicant1_outerface_complete_scan() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-scan",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (FiW1Wpa_supplicant1OuterfaceIface, handle_scan),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    2,
    G_TYPE_DBUS_METHOD_INVOCATION, G_TYPE_VARIANT);

}

/**
 * fi_w1_wpa_supplicant1_outerface_call_scan:
 * @proxy: A #FiW1Wpa_supplicant1OuterfaceProxy.
 * @arg_args: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-fi-w1-wpa_supplicant1-Outerface.Scan">Scan()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call fi_w1_wpa_supplicant1_outerface_call_scan_finish() to get the result of the operation.
 *
 * See fi_w1_wpa_supplicant1_outerface_call_scan_sync() for the synchronous, blocking version of this method.
 */
void
fi_w1_wpa_supplicant1_outerface_call_scan (
    FiW1Wpa_supplicant1Outerface *proxy,
    GVariant *arg_args,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Scan",
    g_variant_new ("(@a{sv})",
                   arg_args),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * fi_w1_wpa_supplicant1_outerface_call_scan_finish:
 * @proxy: A #FiW1Wpa_supplicant1OuterfaceProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to fi_w1_wpa_supplicant1_outerface_call_scan().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with fi_w1_wpa_supplicant1_outerface_call_scan().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
fi_w1_wpa_supplicant1_outerface_call_scan_finish (
    FiW1Wpa_supplicant1Outerface *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * fi_w1_wpa_supplicant1_outerface_call_scan_sync:
 * @proxy: A #FiW1Wpa_supplicant1OuterfaceProxy.
 * @arg_args: Argument to pass with the method invocation.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-fi-w1-wpa_supplicant1-Outerface.Scan">Scan()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See fi_w1_wpa_supplicant1_outerface_call_scan() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
fi_w1_wpa_supplicant1_outerface_call_scan_sync (
    FiW1Wpa_supplicant1Outerface *proxy,
    GVariant *arg_args,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Scan",
    g_variant_new ("(@a{sv})",
                   arg_args),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * fi_w1_wpa_supplicant1_outerface_complete_scan:
 * @object: A #FiW1Wpa_supplicant1Outerface.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-fi-w1-wpa_supplicant1-Outerface.Scan">Scan()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
fi_w1_wpa_supplicant1_outerface_complete_scan (
    FiW1Wpa_supplicant1Outerface *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * FiW1Wpa_supplicant1OuterfaceProxy:
 *
 * The #FiW1Wpa_supplicant1OuterfaceProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * FiW1Wpa_supplicant1OuterfaceProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #FiW1Wpa_supplicant1OuterfaceProxy.
 */

struct _FiW1Wpa_supplicant1OuterfaceProxyPrivate
{
  GData *qdata;
};

static void fi_w1_wpa_supplicant1_outerface_proxy_iface_init (FiW1Wpa_supplicant1OuterfaceIface *iface);

#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (FiW1Wpa_supplicant1OuterfaceProxy, fi_w1_wpa_supplicant1_outerface_proxy, G_TYPE_DBUS_PROXY,
                         G_ADD_PRIVATE (FiW1Wpa_supplicant1OuterfaceProxy)
                         G_IMPLEMENT_INTERFACE (TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE, fi_w1_wpa_supplicant1_outerface_proxy_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (FiW1Wpa_supplicant1OuterfaceProxy, fi_w1_wpa_supplicant1_outerface_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE, fi_w1_wpa_supplicant1_outerface_proxy_iface_init));

#endif
static void
fi_w1_wpa_supplicant1_outerface_proxy_finalize (GObject *object)
{
  FiW1Wpa_supplicant1OuterfaceProxy *proxy = FI_W1_WPA_SUPPLICANT1_OUTERFACE_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (fi_w1_wpa_supplicant1_outerface_proxy_parent_class)->finalize (object);
}

static void
fi_w1_wpa_supplicant1_outerface_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
fi_w1_wpa_supplicant1_outerface_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec G_GNUC_UNUSED)
{
}

static void
fi_w1_wpa_supplicant1_outerface_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name G_GNUC_UNUSED,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_fi_w1_wpa_supplicant1_outerface_interface_info.parent_struct, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
fi_w1_wpa_supplicant1_outerface_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  FiW1Wpa_supplicant1OuterfaceProxy *proxy = FI_W1_WPA_SUPPLICANT1_OUTERFACE_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_fi_w1_wpa_supplicant1_outerface_interface_info.parent_struct, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_fi_w1_wpa_supplicant1_outerface_interface_info.parent_struct, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
fi_w1_wpa_supplicant1_outerface_proxy_init (FiW1Wpa_supplicant1OuterfaceProxy *proxy)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  proxy->priv = fi_w1_wpa_supplicant1_outerface_proxy_get_instance_private (proxy);
#else
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE_PROXY, FiW1Wpa_supplicant1OuterfaceProxyPrivate);
#endif

  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), fi_w1_wpa_supplicant1_outerface_interface_info ());
}

static void
fi_w1_wpa_supplicant1_outerface_proxy_class_init (FiW1Wpa_supplicant1OuterfaceProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = fi_w1_wpa_supplicant1_outerface_proxy_finalize;
  gobject_class->get_property = fi_w1_wpa_supplicant1_outerface_proxy_get_property;
  gobject_class->set_property = fi_w1_wpa_supplicant1_outerface_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = fi_w1_wpa_supplicant1_outerface_proxy_g_signal;
  proxy_class->g_properties_changed = fi_w1_wpa_supplicant1_outerface_proxy_g_properties_changed;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (FiW1Wpa_supplicant1OuterfaceProxyPrivate));
#endif
}

static void
fi_w1_wpa_supplicant1_outerface_proxy_iface_init (FiW1Wpa_supplicant1OuterfaceIface *iface)
{
}

/**
 * fi_w1_wpa_supplicant1_outerface_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-fi-w1-wpa_supplicant1-Outerface.top_of_page">fi.w1.wpa_supplicant1.Outerface</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call fi_w1_wpa_supplicant1_outerface_proxy_new_finish() to get the result of the operation.
 *
 * See fi_w1_wpa_supplicant1_outerface_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
fi_w1_wpa_supplicant1_outerface_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "fi.w1.wpa_supplicant1.Interface", NULL);
}

/**
 * fi_w1_wpa_supplicant1_outerface_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to fi_w1_wpa_supplicant1_outerface_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with fi_w1_wpa_supplicant1_outerface_proxy_new().
 *
 * Returns: (transfer full) (type FiW1Wpa_supplicant1OuterfaceProxy): The constructed proxy object or %NULL if @error is set.
 */
FiW1Wpa_supplicant1Outerface *
fi_w1_wpa_supplicant1_outerface_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return FI_W1_WPA_SUPPLICANT1_OUTERFACE (ret);
  else
    return NULL;
}

/**
 * fi_w1_wpa_supplicant1_outerface_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-fi-w1-wpa_supplicant1-Outerface.top_of_page">fi.w1.wpa_supplicant1.Outerface</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See fi_w1_wpa_supplicant1_outerface_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type FiW1Wpa_supplicant1OuterfaceProxy): The constructed proxy object or %NULL if @error is set.
 */
FiW1Wpa_supplicant1Outerface *
fi_w1_wpa_supplicant1_outerface_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "fi.w1.wpa_supplicant1.Interface", NULL);
  if (ret != NULL)
    return FI_W1_WPA_SUPPLICANT1_OUTERFACE (ret);
  else
    return NULL;
}


/**
 * fi_w1_wpa_supplicant1_outerface_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like fi_w1_wpa_supplicant1_outerface_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call fi_w1_wpa_supplicant1_outerface_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See fi_w1_wpa_supplicant1_outerface_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
fi_w1_wpa_supplicant1_outerface_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "fi.w1.wpa_supplicant1.Interface", NULL);
}

/**
 * fi_w1_wpa_supplicant1_outerface_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to fi_w1_wpa_supplicant1_outerface_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with fi_w1_wpa_supplicant1_outerface_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type FiW1Wpa_supplicant1OuterfaceProxy): The constructed proxy object or %NULL if @error is set.
 */
FiW1Wpa_supplicant1Outerface *
fi_w1_wpa_supplicant1_outerface_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return FI_W1_WPA_SUPPLICANT1_OUTERFACE (ret);
  else
    return NULL;
}

/**
 * fi_w1_wpa_supplicant1_outerface_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like fi_w1_wpa_supplicant1_outerface_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See fi_w1_wpa_supplicant1_outerface_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type FiW1Wpa_supplicant1OuterfaceProxy): The constructed proxy object or %NULL if @error is set.
 */
FiW1Wpa_supplicant1Outerface *
fi_w1_wpa_supplicant1_outerface_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "fi.w1.wpa_supplicant1.Interface", NULL);
  if (ret != NULL)
    return FI_W1_WPA_SUPPLICANT1_OUTERFACE (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * FiW1Wpa_supplicant1OuterfaceSkeleton:
 *
 * The #FiW1Wpa_supplicant1OuterfaceSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * FiW1Wpa_supplicant1OuterfaceSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #FiW1Wpa_supplicant1OuterfaceSkeleton.
 */

struct _FiW1Wpa_supplicant1OuterfaceSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_fi_w1_wpa_supplicant1_outerface_skeleton_handle_method_call (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  FiW1Wpa_supplicant1OuterfaceSkeleton *skeleton = FI_W1_WPA_SUPPLICANT1_OUTERFACE_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_fi_w1_wpa_supplicant1_outerface_skeleton_handle_get_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  FiW1Wpa_supplicant1OuterfaceSkeleton *skeleton = FI_W1_WPA_SUPPLICANT1_OUTERFACE_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_fi_w1_wpa_supplicant1_outerface_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_fi_w1_wpa_supplicant1_outerface_skeleton_handle_set_property (
  GDBusConnection *connection G_GNUC_UNUSED,
  const gchar *sender G_GNUC_UNUSED,
  const gchar *object_path G_GNUC_UNUSED,
  const gchar *interface_name G_GNUC_UNUSED,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  FiW1Wpa_supplicant1OuterfaceSkeleton *skeleton = FI_W1_WPA_SUPPLICANT1_OUTERFACE_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_fi_w1_wpa_supplicant1_outerface_interface_info.parent_struct, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _fi_w1_wpa_supplicant1_outerface_skeleton_vtable =
{
  _fi_w1_wpa_supplicant1_outerface_skeleton_handle_method_call,
  _fi_w1_wpa_supplicant1_outerface_skeleton_handle_get_property,
  _fi_w1_wpa_supplicant1_outerface_skeleton_handle_set_property,
  {NULL}
};

static GDBusInterfaceInfo *
fi_w1_wpa_supplicant1_outerface_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return fi_w1_wpa_supplicant1_outerface_interface_info ();
}

static GDBusInterfaceVTable *
fi_w1_wpa_supplicant1_outerface_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton G_GNUC_UNUSED)
{
  return (GDBusInterfaceVTable *) &_fi_w1_wpa_supplicant1_outerface_skeleton_vtable;
}

static GVariant *
fi_w1_wpa_supplicant1_outerface_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  FiW1Wpa_supplicant1OuterfaceSkeleton *skeleton = FI_W1_WPA_SUPPLICANT1_OUTERFACE_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_fi_w1_wpa_supplicant1_outerface_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _fi_w1_wpa_supplicant1_outerface_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _fi_w1_wpa_supplicant1_outerface_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _fi_w1_wpa_supplicant1_outerface_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "fi.w1.wpa_supplicant1.Outerface", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
fi_w1_wpa_supplicant1_outerface_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void fi_w1_wpa_supplicant1_outerface_skeleton_iface_init (FiW1Wpa_supplicant1OuterfaceIface *iface);
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
G_DEFINE_TYPE_WITH_CODE (FiW1Wpa_supplicant1OuterfaceSkeleton, fi_w1_wpa_supplicant1_outerface_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_ADD_PRIVATE (FiW1Wpa_supplicant1OuterfaceSkeleton)
                         G_IMPLEMENT_INTERFACE (TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE, fi_w1_wpa_supplicant1_outerface_skeleton_iface_init));

#else
G_DEFINE_TYPE_WITH_CODE (FiW1Wpa_supplicant1OuterfaceSkeleton, fi_w1_wpa_supplicant1_outerface_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE, fi_w1_wpa_supplicant1_outerface_skeleton_iface_init));

#endif
static void
fi_w1_wpa_supplicant1_outerface_skeleton_finalize (GObject *object)
{
  FiW1Wpa_supplicant1OuterfaceSkeleton *skeleton = FI_W1_WPA_SUPPLICANT1_OUTERFACE_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (fi_w1_wpa_supplicant1_outerface_skeleton_parent_class)->finalize (object);
}

static void
fi_w1_wpa_supplicant1_outerface_skeleton_init (FiW1Wpa_supplicant1OuterfaceSkeleton *skeleton)
{
#if GLIB_VERSION_MAX_ALLOWED >= GLIB_VERSION_2_38
  skeleton->priv = fi_w1_wpa_supplicant1_outerface_skeleton_get_instance_private (skeleton);
#else
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE_SKELETON, FiW1Wpa_supplicant1OuterfaceSkeletonPrivate);
#endif

  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
fi_w1_wpa_supplicant1_outerface_skeleton_class_init (FiW1Wpa_supplicant1OuterfaceSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = fi_w1_wpa_supplicant1_outerface_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = fi_w1_wpa_supplicant1_outerface_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = fi_w1_wpa_supplicant1_outerface_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = fi_w1_wpa_supplicant1_outerface_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = fi_w1_wpa_supplicant1_outerface_skeleton_dbus_interface_get_vtable;

#if GLIB_VERSION_MAX_ALLOWED < GLIB_VERSION_2_38
  g_type_class_add_private (klass, sizeof (FiW1Wpa_supplicant1OuterfaceSkeletonPrivate));
#endif
}

static void
fi_w1_wpa_supplicant1_outerface_skeleton_iface_init (FiW1Wpa_supplicant1OuterfaceIface *iface)
{
}

/**
 * fi_w1_wpa_supplicant1_outerface_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-fi-w1-wpa_supplicant1-Outerface.top_of_page">fi.w1.wpa_supplicant1.Outerface</link>.
 *
 * Returns: (transfer full) (type FiW1Wpa_supplicant1OuterfaceSkeleton): The skeleton object.
 */
FiW1Wpa_supplicant1Outerface *
fi_w1_wpa_supplicant1_outerface_skeleton_new (void)
{
  return FI_W1_WPA_SUPPLICANT1_OUTERFACE (g_object_new (TYPE_FI_W1_WPA_SUPPLICANT1_OUTERFACE_SKELETON, NULL));
}

